name: Code Coverage

on: [pull_request]

jobs:
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: Bogdanp/setup-racket@v1.5
        with:
          version: stable
      - run: raco pkg install --batch --auto cover cover-coveralls
      - run: raco pkg install --batch --auto --link --name resyntax
      - run: raco cover --format coveralls --suppress-log-execution --package resyntax
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
